In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [14]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
a = np.array([[1,'3',3,4,5],[1,2,3,4,5]] , dtype = int)
print(a)
print(type(a))

[[1 3 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>


In [13]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

c = a+b
print(c)

[ 2  4  6  8 10]


In [19]:
a = np.array([1,2,3,4,5])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


1
(5,)
5
int64


In [32]:
a = np.ones((3,3) , dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
a = np.zeros((3,3), dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
a = np.full((3,3) ,5, dtype = int)
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [44]:
a = np.empty(4 , dtype = int)
a

array([            0, 2846076991120, 2846076991680, 2846076994960])

In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a = np.array([0,0,0,0,1,0,0,0,0,0])
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [49]:
a = np.zeros(10 , dtype = int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [53]:
a = np.arange(0 ,10 , dtype = int)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a = np.empty(2, dtype=int , order = 'c')

a

array([0, 0])