In [5]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Array Shape and Reshape

In [17]:
arr.shape

(9,)

In [30]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)

In [31]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Indexing , Slicing , filtering 

In [34]:
arr[1:5]

array([2, 3, 4, 5])

In [35]:
arr[arr > 5]

array([6, 7, 8, 9])

In [36]:
np.where(arr > 5)

(array([5, 6, 7, 8]),)

In [54]:
arr1 = np.random.randint(0,10,9)

np.add(arr,arr1)



array([ 6, 10,  3,  4, 12, 13, 12,  8, 16])

In [69]:
np.subtract(arr , arr1)

array([-4, -6,  3,  4, -2, -1,  2,  8,  2])

In [109]:
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
print(f"mean {int(mean)} median {int(median)} std {int(std)}")

print(np.min(arr))
print(np.max(arr))
print(np.percentile(arr,75))

mean 5 median 5 std 2
1
9
7.0


In [8]:
np.random.rand(3,3
              )

array([[0.28653482, 0.21655667, 0.89792059],
       [0.25162232, 0.9710148 , 0.55678322],
       [0.51892358, 0.89799068, 0.90043656]])

In [113]:
np.random.randn(3,3)

array([[-1.11799017,  0.92116089, -1.16023374],
       [ 0.27339736,  0.51254132,  0.63219027],
       [ 0.34844508, -0.04385818, -1.07357955]])

In [44]:
d = np.random.randint(0,10,(3,4))
print(d)
print(np.sort(d))
print(np.min(d))
print(np.max(d))
print(np.mean(d))
print(np.median(d))
print(np.std(d))


[[2 1 8 8]
 [0 3 0 4]
 [4 0 8 0]]
[[1 2 8 8]
 [0 0 3 4]
 [0 0 4 8]]
0
8
3.1666666666666665
2.5
3.131382371342656


In [116]:
np.random.seed(42)

In [118]:
np.sort(arr1)

array([0, 0, 0, 5, 5, 7, 7, 7, 8], dtype=int32)

In [120]:
np.unique(arr1)

array([0, 5, 7, 8], dtype=int32)