In [15]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4,5,6])
arr * 5

array([ 5, 10, 15, 20, 25, 30])

In [31]:
arr_reshape = arr.reshape(1,6)
arr_reshape


array([[1, 2, 3, 4, 5, 6]])

In [35]:
arr2 = np.array([0,9,8,7,6,8])

print(arr + arr2)
print(arr * arr2)

[ 1 11 11 11 11 14]
[ 0 18 24 28 30 48]


In [39]:
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
print(mean)
print(median)
print(std)
print(f"Mean {mean} Median {median} Std {std}")

3.5
3.5
1.707825127659933
Mean 3.5 Median 3.5 Std 1.707825127659933


In [41]:
filter_data = arr[arr > mean]
print(filter_data)

[4 5 6]


In [58]:
arr3 = np.random.randint(0,10,(10))
arr3

array([9, 3, 6, 4, 3, 7, 3, 6, 8, 5], dtype=int32)

In [62]:
arr3[arr3 > 5]
arr3[arr3 % 2 == 0]

array([6, 4, 6, 8], dtype=int32)

In [69]:
print(np.min(arr3))
print(np.max(arr3))



3
9
